galaxy_info:
  author: Mohan L
  description: An Ansible role for installing and configuring Supervisor (process state manager) for Linux.
  company: Mohan
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
    - precise
dependencies: []
